// Generated by app-wabbit-dev setup. Do not edit by hand.
// managed-integrity-v1: CN312dAhhRt
//
// This file is generated from workspace configuration in root.clj.
// To change it, update root.clj and regenerate
// with the dev command, for example:
//   dev setup <project-or-repo>
// For durable imperative Gradle logic, use build.extra.gradle.kts beside this file.
// Direct edits to this file will be overwritten the next time setup runs.

import org.jetbrains.dokka.gradle.DokkaExtension
import org.jetbrains.dokka.gradle.engine.plugins.DokkaHtmlPluginParameters
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

fun String.parseWabbitBooleanFlag(flagName: String): Boolean =
    when (trim().lowercase()) {
        "true" -> true
        "false" -> false
        else -> error("$flagName must be true or false, got '$this'")
    }

val useMavenLocalArtifacts =
    providers.gradleProperty("wabbit.useMavenLocalArtifacts")
        .orElse(providers.environmentVariable("WABBIT_USE_MAVEN_LOCAL_ARTIFACTS"))
        .map { it.parseWabbitBooleanFlag("wabbit.useMavenLocalArtifacts") }
        .orElse(false)
        .get()

repositories {
    if (useMavenLocalArtifacts) {
        mavenLocal {
            content {
                includeGroup("one.wabbit")
                includeGroupByRegex("one\\.wabbit\\..+")
            }
        }
    }
    google()
    mavenCentral()

    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://jitpack.io")
}

group   = "one.wabbit"

version = "1.0.0"

plugins {
    kotlin("jvm")
    id("org.jetbrains.dokka")
    id("org.jetbrains.kotlinx.kover")

    kotlin("plugin.serialization")

    id("one.wabbit.no-globals")

    id("one.wabbit.acyclic")

    id("maven-publish")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "one.wabbit"
            artifactId = "cc-lib-modules"
            version = project.version.toString()
            from(components["java"])
        }
    }
}

dependencies {
    implementation("one.wabbit:kotlin-data-need:1.2.0")
    implementation("one.wabbit:kotlin-data:3.0.0")
    implementation("one.wabbit:kotlin-extra-reflection:1.0.1")
    implementation("one.wabbit:kotlin-minilog:1.0.2")
    implementation("one.wabbit:kotlin-graph-toposort:2.0.0")
    implementation("one.wabbit:kotlin-levenshtein:1.1.0")

    testImplementation(kotlin("test"))

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.9.0")

    implementation("io.ktor:ktor-serialization-kotlinx-json:3.3.0")
    implementation("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
}

java {
    targetCompatibility = JavaVersion.toVersion(21)
    sourceCompatibility = JavaVersion.toVersion(21)
}

val configuredVersionString = version.toString()

tasks.register("printVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        println(inputs.properties["configuredVersion"])
    }
}

tasks.register("assertReleaseVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(!versionString.endsWith("+dev-SNAPSHOT")) {
            "Release publishing requires a non-snapshot version, got $versionString"
        }
        val refType = System.getenv("GITHUB_REF_TYPE") ?: ""
        val refName = System.getenv("GITHUB_REF_NAME") ?: ""
        if (refType == "tag" && refName.isNotBlank()) {
            val expectedTag = "v$versionString"
            require(refName == expectedTag) {
                "Git tag $refName does not match project version $versionString"
            }
        }
    }
}

tasks.register("assertSnapshotVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(versionString.endsWith("+dev-SNAPSHOT")) {
            "Snapshot publishing requires a +dev-SNAPSHOT version, got $versionString"
        }
        require((System.getenv("GITHUB_REF_TYPE") ?: "") != "tag") {
            "Snapshot publishing must not run from a tag ref"
        }
    }
}

tasks {
    withType<Test> {
        jvmArgs("-ea")

    }
    withType<JavaCompile> {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
    }
    withType<Javadoc> {
        options.encoding = Charsets.UTF_8.name()
    }

    withType<KotlinCompile> {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
            freeCompilerArgs.add("-Xcontext-parameters")

            freeCompilerArgs.addAll(
                "-P",
                "plugin:one.wabbit.acyclic:compilationUnits=enabled",
            )

            freeCompilerArgs.addAll(
                "-P",
                "plugin:one.wabbit.acyclic:declarations=enabled",
            )

        }
    }

    jar {
        setProperty("zip64", true)

    }
}

// Kover Configuration
kover {
    // useJacoco() // This is the default, can be specified if you want to be explicit
    // reports {
    //     // Configure reports for the default test task.
    //     // Kover tries to infer the variant for simple JVM projects.
    //     // If you have specific build types/flavors, you'd configure them here as variants.
    //     variant() { // Or remove "debug" for a default JVM setup unless you have variants
    //         html {
    //             // reportDir.set(layout.buildDirectory.dir("reports/kover/html")) // Uncomment to customize output
    //             // title.set("cc-lib-modules Code Coverage") // Uncomment to customize title
    //         }
    //         xml {
    //             // reportFile.set(layout.buildDirectory.file("reports/kover/coverage.xml")) // Uncomment to customize output
    //         }
    //     }
    // }
}

plugins.withId("org.jetbrains.dokka") {
    afterEvaluate {
        extensions.findByType(DokkaExtension::class)?.apply {
            moduleName.set("cc-lib-modules")
            dokkaPublications.named("html").configure {
                suppressInheritedMembers.set(true)
                failOnWarning.set(true)
            }
            dokkaSourceSets.named("main").configure {
                val dokkaModuleFile = file("docs/dokka-module.md")
                if (dokkaModuleFile.exists()) {
                    includes.from(dokkaModuleFile)
                }

                sourceLink {
                    localDirectory.set(file("src/main/kotlin"))
                    remoteUrl("https://github.com/corsaircraft/cc-lib-modules/tree/master/src/main/kotlin")
                    remoteLineSuffix.set("#L")
                }

            }
            pluginsConfiguration.named(DokkaHtmlPluginParameters.DOKKA_HTML_PARAMETERS_NAME).configure {
                (this as DokkaHtmlPluginParameters).footerMessage.set("(c) Wabbit Consulting Corporation")
            }
        }
    }
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
